spring:
  profiles:
    active: dev
  name: dev-YAML
  environment: dev

  # DB configurations.
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate